_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 1000

log_every_n_steps: 6

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
# if set to value greater than max_epochs, validation will be skipped
check_val_every_n_epoch: 9999

# number of validation steps to run before training
num_sanity_val_steps: 0

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: True
