defaults:
  - _self_
  - /data: cellular_graph
  - /model: bgrl_phenotype
  - /callbacks: pretrain_phenotype
  - /logger: csv
  - /trainer: default
  - /paths: default
  - /extras: default

# task name, determines output directory path
task_name: "pretrain"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 44
