# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/f1_best"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 10

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed} # seed for random number generator
      n_startup_trials: 5 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      pretrain.model.net.encoder.drop_ratio: interval(0.1, 0.5)
      pretrain.model.optimizer.lr: interval(0.0001, 0.01)
      pretrain.model.optimizer.weight_decay: interval(0.0, 0.1)
      pretrain.model.mm: interval(0.9, 0.99)
      #pretrain.model.drop_edge_p1: interval(0.1, 0.4)
      #pretrain.model.drop_edge_p2: interval(0.1, 0.4)
      #pretrain.model.drop_feat_p1: interval(0.1, 0.4)
      #pretrain.model.drop_feat_p2: interval(0.1, 0.4)
      pretrain.model.mu: interval(0.1, 0.4)
      pretrain.model.p_lambda: interval(0.4, 0.6)
      #pretrain.model.p_rewire: interval(0.1, 0.4)
      pretrain.model.feature_noise_std: interval(0.1, 0.4)
      pretrain.model.p_add: interval(0.05, 0.2)
      pretrain.model.k_add: choice(0, 1, 2, 3, 4, 5)

      finetune.model.net.drop_ratio: interval(0.1, 0.5)
      finetune.model.optimizer.lr: interval(0.000001, 0.0001)
      finetune.model.optimizer.weight_decay: interval(0.0, 0.1)
      finetune.model.mm: interval(0.9, 0.99)
