_target_: src.models.bgrl_module.BGRLLitModule

net:
  _target_: src.models.components.bgrl.BGRL
  encoder:
    _target_: src.models.components.two_layer_gcn.TwoLayerGCN
    input_size: 50
    hidden_size: 32
    output_size: 16
    dropout: 0.5
  projector:
    _target_: src.models.components.bgrl_projector.BGRLProjector
    input_size: 16
    output_size: 16
    hidden_size: 32

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.02
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10


compile: false                                          # compile model for faster training with pytorch 2.0
augmentation: 'baseline'                                # augmetation strategy, either baseline or advanced
mm: 0.92                                                # momentum for moving average of target encoder
drop_edge_p1: 0.1                                       # drop edge probability for first augmentation
drop_edge_p2: 0.1                                       # drop edge probability for second augmentation
drop_feat_p1: 0.1                                       # drop feature probability for first augmentation
drop_feat_p2: 0.1                                       # drop feature probability for second augmentation
#warmup_steps: 1000                                     # number of warmup steps for learning rate scheduler
processed_dir: ${paths.data_dir}/domain/processed/     # directory for processed data

