# @package _global_

defaults:
  - _self_
  - data: spatial_omics
  - model: bgrl_domain
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# seed for random number generators in pytorch, numpy and python.random
seed: 02092000
