# @package _global_

defaults:
  - _self_
  - logger: null
  - paths: default
  - extras: default
  - hydra: default


task_name: "preprocess"

tags: ["dev"]

input_files:
  - "${paths.data_dir}/domain/raw/MERFISH_small1.h5ad"
  - "${paths.data_dir}/domain/raw/MERFISH_small2.h5ad"
  - "${paths.data_dir}/domain/raw/MERFISH_small3.h5ad"
  - "${paths.data_dir}/domain/raw/MERFISH_small4.h5ad"
  - "${paths.data_dir}/domain/raw/MERFISH_small5.h5ad"
  - "${paths.data_dir}/domain/raw/STARmap1.h5ad"
  - "${paths.data_dir}/domain/raw/STARmap2.h5ad"
  - "${paths.data_dir}/domain/raw/STARmap3.h5ad"
  - "${paths.data_dir}/domain/raw/STARmap4.h5ad"
  - "${paths.data_dir}/domain/raw/BaristaSeq1.h5ad"
  - "${paths.data_dir}/domain/raw/BaristaSeq2.h5ad"
  - "${paths.data_dir}/domain/raw/BaristaSeq3.h5ad"

data_output_dir: "${paths.data_dir}/domain/processed"
min_cells: 3
min_genes: 3
graph_method: "knn"
n_neighbors: 10
save_combined_dataset: true